language: kotlin
jdk:
  - oraclejdk9
before_script:
  - chmod +x gradlew
install:
  - pip install --user codecov
script:
  - ./gradlew --version
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - codecov